### ISSUE TITLE
Pipeline fails normalizing 1 mark - file missing

### ISSUE THREAD

**Issue by michael-imbeault** [guanjue/S3V2_IDEAS_ESMP#1]
Hi there,

Been trying to use S3Norm to normalize bigwigs from the NIH Roadmap project, and at the moment the pipeline is failing at a specific step where it is looking for a file ending with "max1.bedgraph.S3.bedgraph" that doesn't exist. From the recent commits it looks like this is still active development, so let me know if this is the current state of things, or if its a simple fix!

**Comment by guanjue** [comment]
Hi, it is a small bug in the 1mk mode. It has been fixed now.

**Comment by michael-imbeault** [comment]
That fixed it, thanks!
