### ISSUE TITLE
How is S3V2 applied to each epigenetic mark

### ISSUE THREAD

**Issue by yztxwd** [guanjue/S3V2_IDEAS_ESMP#4]
Hi Guanjue:

I'm curious about how S3V2 was applied to normalize each epigenetic track, my understanding is S3V2 normalization is applied to each type of epigenetic mark respectively, so if there are 2 epigenetic marks (i.e., H3.3 and H2A.Z), S3V2 would be called twice, one for each, is that correct?

And I also wonder if there is a way to let the pipeline stop when normalization is done, because I only need the normalized bigwig files, IDEAS usually takes a lot of time to run and it's not very convenient to kill the process every time.

Thanks!

**Comment by guanjue** [comment]
Yes, the S3V2-IDEAS pipeline apply S3norm version1 to adjust sequencing depth and signal to noise ratio across of the average signal tracks for all epigenetic marks first. Then, it will use S3V2 to normalize each sample of each feature against the new average signal track.

You can set run_ideas='F' in "run_S3V2_IDEAS_ESMP.sh" to just running the normalization part.
