### ISSUE TITLE
How to extract summary info from the HMM model? and How to apply trained HMM model to new data?

### ISSUE THREAD

**Issue by fatyang799** [guanjue/S3V2_IDEAS_ESMP#6]
Hi Guanjue:

Recently, I read the paper of chromHMM. And some ideas from chromHMM make me want to apply to IDEAS. But I don't know how to achieve these with IDEAS. I would greatly appreciate if you could answer these questions.
1. As an HMM model, the model should have emission parameters and transition parameters. I know the emission parameters can be get by follow script. My question is, where can I get the transition parameters of the model?
```R
d = read.table('File.para', header=T, sep=' ', comment.char='~')
ds = d[,2:(num_of_features+1)] / d[,1]
```
2. I want to know the goodness fit of the model to the data. To achieve this, I can calculate the AIC or BIC value for the model. But how do I do to get AIC or BIC value?

3. After I get an HMM model in one data set, how do I apply this model to another data set to assign chromatin states?

Many thanks!

**Comment by guanjue** [comment]
Unfortunately, the transition parameters and the goodness fit of the model  are not saved in the IDEAS package.
Also, only the emission matrix can be applied to other IDEAS runs by adding "otherpara= /file_path_to_the_para_file" in the run_IDEAS.parafile

**Comment by fatyang799** [comment]
Thanks for your reply.   :)
If I meet any questions else, I'll start a new issue. Thanks!
