### ISSUE TITLE
Imputation function in IDEAS

### ISSUE THREAD

**Issue by fatyang799** [guanjue/S3V2_IDEAS_ESMP#9]
Hi!

After I solve the NAs in the output files of S3V2 packages, I found another question when I run the IDEAS. I remember the IDEAS can impute missing data when lacking a few markers' data. But according to the log file, the program seems to close the impute function. But to my surprise, the IDEAS still output the genome segmentation result.

So my question is,

1. How much of an effect does the presence or absence of imputation have on the result?
2. How to open the imputation function in IDEAS?
3. What is the difference in setting between `specify which marks to be imputed` or `All` or `None`?

![image](https://user-images.githubusercontent.com/52167840/226569979-39a7fc45-e286-4dad-92e1-3bd8a75d6067.png)

**Comment by fatyang799** [comment]
I read the published paper (Y. Zhang, and S. Mahony, PLoS Comput Biol, 2019.) and it seems that the imputation function of IDEAS is not used to serve for segmentation. Instead, it is used to get missing data after the segmentation is completed.

So the imputation function is not necessary for running IDEAS. Am I understanding this correctly? 😅

**Comment by guanjue** [comment]
Yes, this is correct. The imputation function is not used for running IDEAS

Personally, I haven't used the imputation function. But you can change the following parameter in the *.parafile 
impute= None            #specify which marks to be imputed; or All or None

**Comment by fatyang799** [comment]
Thank you for your patient and quick response!
